import datetime as dt
now=dt.datetime.now()
time = now.time()
print(time)
date = now.date()
print(date)
stdate=now.strftime("%d/%m/%y")
print(stdate)
time=now.strftime("%H:%M:%S")
print(time)
year=now.strftime("%Y")
print(year)
stdate=now.strftime("%d")
print(stdate)
stdate=now.strftime("%A")
print(stdate)
stdate=now.strftime("%a")
print(stdate)
stdate=now.strftime("%B")
print(stdate)
stdate=now.strftime("%b")
print(stdate)
stdate=now.strftime("%H")
print(stdate)
stdate=now.strftime("%I")
print(stdate)
stdate=now.strftime("%f")
print(stdate)
stdate=now.strftime("%F")
print(stdate)
stdate=now.strftime("%p")
print(stdate)
stdate=now.strftime("%c")
print(stdate)
stdate=now.strftime("%x")
print(stdate)
# stdate=now.strftime("%Z")
# print(stdate)
# stdate=now.strftime("%z")
# print(stdate)
stdate=now.strftime("%j")
print(stdate)
stdate=now.strftime("%w")
print(stdate)
stdate=now.strftime("%W")
print(stdate)
stdate=now.strftime("%U")
print(stdate)
print("Time In 24 Hours Format",now.strftime("%H-%M-%S"))
print("Time In 12 Hours Format",now.strftime("%I-%M-%S"))
import os
a=os.listdrives()
print(a)
